using Oaza.Domain.Enums;

namespace Oaza.Domain.Entities;

/// <summary>
/// A payment made by a house. Either a regular monthly advance (Type=Advance,
/// one per house per month) or an ad-hoc top-up (Type=Doplatek, repeatable).
/// The amount is split into the three pricing components — water, pump
/// electricity, common base — mirroring <see cref="AdvanceSettings"/>.
/// </summary>
public class AdvancePayment
{
    public string HouseId { get; set; } = string.Empty;
    public int Year { get; set; }
    public int Month { get; set; }

    /// <summary>Total amount = WaterAmount + ElectricityAmount + CommonAmount.</summary>
    public decimal Amount { get; set; }

    /// <summary>Water portion of the payment (CZK).</summary>
    public decimal WaterAmount { get; set; }

    /// <summary>Pump-electricity portion of the payment (CZK).</summary>
    public decimal ElectricityAmount { get; set; }

    /// <summary>Common-base portion of the payment (CZK).</summary>
    public decimal CommonAmount { get; set; }

    public DateTime PaymentDate { get; set; }

    public PaymentType Type { get; set; } = PaymentType.Advance;

    /// <summary>Optional free-text note (mainly for doplatky).</summary>
    public string? Note { get; set; }

    /// <summary>
    /// True when this doplatek was auto-generated by closing a water billing
    /// period with a fund draw (see CloseBillingPeriodUseCase), not manually
    /// entered by an admin. Drives the "Z fondu" badge in the payment history.
    /// </summary>
    public bool IsFundTransfer { get; set; }

    /// <summary>
    /// Storage RowKey. For advances this is "YYYY-MM" (computed from Year/Month).
    /// For doplatky it is a unique key "D-{invertedTicks}-{guid8}" assigned at creation.
    /// Populated on read; used to address a specific payment for update/delete.
    /// </summary>
    public string RowKey { get; set; } = string.Empty;

    /// <summary>
    /// The date used to decide which billing period this payment belongs to.
    /// A monthly advance belongs to the month it is FOR (Year/Month); an ad-hoc
    /// doplatek belongs to the date it was actually paid (PaymentDate).
    /// </summary>
    public DateTime EffectiveDate() =>
        Type == PaymentType.Doplatek
            ? DateTime.SpecifyKind(PaymentDate, DateTimeKind.Utc)
            : new DateTime(Year, Month, 1, 0, 0, 0, DateTimeKind.Utc);
}
